### PR TITLE
Switch to cibuildwheel for wheel building

### PR DESCRIPTION
**Pull request by djhoese**
Includes adding a pyproject.toml for modern sandbox package building environments.

This should add Python 3.12 wheels too.

### CODE REVIEW

**Comment by djhoese** [comment]
Oh this also drops support for anything below Python 3.9. We had issues building wheels or something for 3.7 iirc and this just takes it a step further.

**Comment by djhoese** [comment]
Putting this in draft until I can be sure that mac arm64 wheels are being made.

**Comment by djhoese** [comment]
@mraspaud hopefully you can review this and merge it and then either make a release or I can make one when I wake up. Then I'll work on pyresample's equivalent of this.

**Review by mraspaud — APPROVED** [review]
LGTM! thanks for doing this, releasing shortly

**Pull request merged**
