### PR TITLE
Add Azure pipelines configuration to build and deploy wheels

### LINKED ISSUE #33: Build wheels for Windows
This is a great module that I use on a regular basis.  Could you please upload windows wheels to PyPi so that Windows users can install this easily?

If anyone needs them in the meantime, here's the binary wheels for 1.3.1 for Windows Python 3.5 and Python 3.6
[wheels.zip](https://github.com/storpipfugl/pykdtree/files/2446361/wheels.zip)

### PR DESCRIPTION
**Pull request by djhoese**
Closes #33 

Builds and uploads wheels for Linux, OSX, and Windows. This is based on similar work I did for VisPy and that I am now trying to do for pyresample. Since I was already doing it for pyresample I copied it over to pykdtree too (sorry @akaszynski I know you were working on this too).

I'm not sure how easy this will be to test without also merging it to the `storpipfugl` copy of the repository and setting of the Azure group/pipeline from there. I haven't completely figured it out for pyresample yet.

### CODE REVIEW

**Comment by akaszynski** [comment]
You can test your branch by creating your own account on Azure devops and then create a new pipeline based on this repo.  Then, after merging you'll have to have the admin login to Azure devops, create a new project, and create a new pipeline based on the `storpipfugl/pykdtree`.

I'd also add `Python3.8` to the test matrix.

**Comment by djhoese** [comment]
Python 3.8 should be one of the defaults. I have it skipping py27 and less than 3.5.

I really haven't figured out how Azure wants projects set up. Would you create an organization for this? Should it be one project per repository?

**Comment by djhoese** [comment]
Oh I see in the Windows section! I'll fix that tomorrow.

**Comment by akaszynski** [comment]
It's been a while since I did the initial setup, but I recall making a personal organization and then adding my projects there.  You might wish to do the same to test out this PR and then either add whoever is in charge of this branch as an admin to the org, or have them create an org on Azure and add the repo once it's merged.

**Comment by akaszynski** [comment]
Any progress on this?  I'd really like to see this implemented.  I've set up accounts on devops before on Azure and can help you out if you'd like.

**Comment by djhoese** [comment]
@akaszynski Again, not a pykdtree core developer, but we've got this working for pyresample. @mraspaud and I ran in to issues with our institutional accounts and tring to make a single Azure organization that let both of us join it. I wouldn't be surprised if @mraspaud is hesitant to try it for this given the difficulty we had. That said, we could probably add pykdtree to the pytroll Azure organization which might simplify this. We still have some more Azure organization testing to work through and with the current state of the world it is hard to find time for this volunteer project.

**Comment by bwoodsend** [comment]
I now know how to do manylinux on TravisCI. And I've got it working for pykdtree. The build is [here](https://travis-ci.com/github/bwoodsend/pykdtree/builds/160949398). Would this be a feasible alternative if Azure is causing complications? I'd really like to see this resolved.

**Comment by djhoese** [comment]
Supersceded by #52

**Pull request closed without merging**
