### PR TITLE
Add 'mask' keyword argument to query method

### LINKED ISSUE #27: Add feature to provide mask when querying for neighbors
I'm willing to add this feature and it is something we have been talking about with pyresample, I just need to find the time to do it and make sure it doesn't break anything. I wanted to see what your opinion was @storpipfugl and put this here to remind myself that I wanted to do it.

This would allow someone to provide a boolean numpy array (or similar) to the query call which would act like an input mask, requiring the query to continue until it found a neighbor that wasn't masked. The use case here is fairly common in meteorological satellite data where you may have multiple datasets that share the same geolocation, but differ on what data pixels are valid. Without doing anything special this can result in neighbor indexes being returned that are actually invalid data points when the next neighbor could be valid. See this example (not tested, but you get the point):

```
>>> from pykdtree.kdtree import KDTree
>>> kd_tree = KDTree([lons, lats])
>>> dist, idx = kd_tree.query(query_pts, k=1)
>>> new_data = data[idx]
```

The simple work around for this situation is to build a new KDTree for every dataset (even though the geolocation going in to the KDTree is the same) but masking out any invalid pixels from the data array.

```
>>> from pykdtree.kdtree import KDTree
>>> kd_tree = KDTree([lons[data != fill], lats[data != fill]])
>>> dist, idx = kd_tree.query(query_pts, k=1)
>>> new_data = data[idx]
```

As you can imagine this can get extremely wasteful to have to rebuild the KDTree every time. Providing this mask parameter would allow you to reuse the same KDTree:

```
>>> from pykdtree.kdtree import KDTree
>>> kd_tree = KDTree([lons, lats])
>>> dist, idx = kd_tree.query(query_pts, k=1, mask=data1 != fill)
>>> new_data1 = data1[idx]
>>> dist, idx = kd_tree.query(query_pts, k=1, mask=data2 != fill)
>>> new_data2 = data2[idx]
```

If this doesn't screw with the performance too much I'd like to implement it some time this year (I can dream). Thoughts @mraspaud @storpipfugl?

### PR DESCRIPTION
**Pull request by davidh-ssec**
This PR includes commits that seem to be out of sync between master and pre-master.

This PR fixes #27 by adding a `mask` keyword argument to the KDTree's query method. This functionality is useful in cases where the validity of the data that will be indexed with the returned indexes may not be the same as the validity of the location `data_pts` passed to the init of the KDTree. 

For example, if you have multiple data arrays with points at the same locations then you could share the KDTree between them. However, let's say data array A has an invalid (masked) pixel at a location, the indexes returned by the KDTree may use that invalid pixel location because it is nearest, but what we really want is the next nearest valid pixel. We could mask the locations originally passed to the KDTree but now the same KDTree can't be used between the various data arrays. By allowing a `mask` array to be passed to query we can have the fast C code keep searching until if finds a valid nearest neighbor.

Note: I created a separate redundant `search_leaf_${DTYPE}_mask` function in an attempt to reduce the effect this extra mask check would have on existing performance. I can merge the functionality with the original function if that is preferred.

### CODE REVIEW

**Comment by sirykd** [comment]
It would be even better to handle a vector of scores (certainties).
Then a binary mask would be a particular case with scores equal either 0 or 1.

As an example, imagine some algorithm that predicts data array to be queried AND an array of probabilities (certainties) for predicted points.

**Comment by davidh-ssec** [comment]
@sirykd What is the condition checked in the C code then? You have a set of probabilities but what are you comparing them to? A threshold? Why not just pass `mask=probabilities > 0.5`?

**Comment by davidh-ssec** [comment]
@sirykd Thinking about it more, if you wanted to do anything more complicated than a mask as I've implemented it, I wonder if it would just be better to include those probabilities as another dimension to the init of the KDTree (you might have to do `1 - probabilities` for proper distancing).

**Comment by sirykd** [comment]
@davidh-ssec A dataset in my situation is meant to have all probabilities equal 1, so all data arrays would have a tail of zeros (= 1 - probabilities). 
In this situation, the added dimensions would contribute the same value to all distances during a query, which is useless.

I propose to scale the contribution of i-th dimension by its probability.
So I wonder if a small modification of calc_dist_* would work.

**Comment by davidh-ssec** [comment]
@sirykd I'm not sure I understand. Are you saying your dataset starts with all probabilities equal to 1? Or are you saying the resulting dataset should have all probabilities equal to 1?

In the first case, why use probabilities at all? In the second case why wouldn't `mask=probabilities < 1` work?

As for scaling the i-th dimension, that does seem possible. So in your use case you have the same KDTree for multiple sets of probabilities? Sorry if I'm misunderstanding something, I only use KDTrees for nearest neighbor calculations.

**Comment by davidh-ssec** [comment]
@storpipfugl Thanks. Any idea when you'll have time for a new release to include this?

**Comment by mraspaud** [comment]
@storpipfugl It would be really nice if this could be released, is there any plans for a new release soon ?

**Pull request merged**
